# Site settings
title: Goal Line Apps
email: hello@goallineapps.com
description: "Edit description in _config.yml"
info: "Edit this info in _config.yml"
message: "Edit this message in _config.yml"
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://goallineapps.github.io" # the base hostname & protocol for your site
twitter_username: goallineapps
# Build settings
author:
    name: Benjamin Hysell
    twitter: benhysell
    url: https://www.benjaminhysell.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: you@CompanyName.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
